version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: tbl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tbl_lab
    ports:
      - "5432:5432"
    volumes:
      - tbl_pgdata:/var/lib/postgresql/data

  catalog-db:
    image: postgres:16-alpine
    container_name: tbl-catalog-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: tbl_catalog
    ports:
      - "5433:5432"
    volumes:
      - tbl_catalog_pgdata:/var/lib/postgresql/data

  neo4j:
    image: neo4j:5-community
    container_name: tbl-neo4j
    restart: unless-stopped
    environment:
      NEO4J_AUTH: neo4j/tblpassword
    ports:
      - "7474:7474" # Interface Web (Neo4j Browser)
      - "7687:7687" # Protocolo Bolt (drivers e conexões)
    volumes:
      - tbl_neo4jdata:/data

volumes:
  tbl_pgdata:
  tbl_neo4jdata:
  tbl_catalog_pgdata:
